### ISSUE TITLE
Type issue with integrations

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/db0#101]
### Environment

"db0": "^0.1.4",
"drizzle-orm": "^0.31.2"

node@20.14

### Reproduction

Write `import { drizzle } from "db0/integrations/drizzle";` in any project and the IDE will tell you that types does not exists.

### Describe the bug

Hey,

I'm trying to use this integration: https://db0.unjs.io/integrations/drizzle but my IDE complains about types.

<img width="1230" alt="Screenshot 2024-07-04 at 19 51 48" src="https://github.com/unjs/db0/assets/45267552/91135519-96e9-4433-9717-270315c91215">

While trying to understand why this could happens, it seems to be an issue with the compilation step where the `../../types` does not exists anymore since every thing move to `dist` except `integrations` and `connectors` because of `mkdist`.

<img width="1224" alt="Screenshot 2024-07-04 at 19 45 46" src="https://github.com/unjs/db0/assets/45267552/36a775ad-6f3c-4e20-ba09-03d3f805a6b2">

**Comment by Wr4th100** [comment]
@Barbapapazes, this worked for me...

```ts
import { drizzle } from "db0/integrations/drizzle/index";
```

**Comment by Barbapapazes** [comment]
> @Barbapapazes, this worked for me...
> 
> ```ts
> import { drizzle } from "db0/integrations/drizzle/index";
> ```

Oohh ok, I'll give a try (but adding `/index` at the end, seems to be more a workaround than a normal behavior).

**Comment by Barbapapazes** [comment]
It works but not really because the type `Database` cannot be resolved so you can pass a string to the Drizzle integration and TypeScript won't complain.

**Comment by pi0** [comment]
fixed with https://github.com/unjs/db0/commit/c48530cda032175f0c0377df4addc99399063774
