### ISSUE TITLE
Supports PGLite

### ISSUE THREAD

**Issue by adrienZ** [unjs/db0#109]
### Describe the feature

Hi ! I head about this new database from eletric-sql: [pglite](https://github.com/electric-sql/pglite).

It's postgres but embedded (just like SQLite). To me it makes it interesting as it could be a very good thing for DX and testing. Plus, drizzle supports it already: https://orm.drizzle.team/learn/latest-releases/drizzle-orm-v0306

Do you think this connector would be worth it ? 

From ChatGPT here is what the connector could look like: https://chatgpt.com/share/782dbe14-5f99-4780-b3f1-bfe8de31adf3

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
I was about to create same issue for a while. Surely that looks a good addition if had a chance, feel free to open a draft PR.

**Comment by adrienZ** [comment]
Sorry for the multiples commits, my PR is ready to be reviwed :)

**Comment by pi0** [comment]
thnx!
