### ISSUE TITLE
✕ unmet peer better-sqlite3@^9.4.3: found 11.2.1

### ISSUE THREAD

**Issue by cdwmhcc** [unjs/db0#111]
### Environment

"db0": "0.1.4"
nodejs: v22.6.0

### Reproduction

pnpm i better-sqlite3

### Describe the bug

Please update the version of the dependency

**Comment by cdwmhcc** [comment]
> I think it is safe to update to v11 as long as you're not using node v16

But it always prompts this:

```
 WARN  Issues with peer dependencies found
apps/dashboard
├─┬ nuxt 3.13.0
│ └─┬ nitropack 2.9.7
│   └─┬ db0 0.1.4
│     ├── ✕ unmet peer better-sqlite3@^9.4.3: found 11.2.1
│     └── ✕ unmet peer drizzle-orm@^0.29.4: found 0.33.0
└─┬ typeorm 0.3.20
  └── ✕ unmet peer better-sqlite3@"^7.1.2 || ^8.0.0 || ^9.0.0": found 11.2.1
```

**Comment by hacknug** [comment]
Yes but it shouldn't be a real problem unless you're experiencing any issues because of it.

**Comment by pi0** [comment]
it will be fixed in next release we relax deps.
