### ISSUE TITLE
Add dialects to connectors

### ISSUE THREAD

**Issue by zsilbi** [unjs/db0#112]
### Describe the feature

The `Connector` type should be extended with an additional `dialect` property.
It should be a string that represents the SQL dialect that the connector supports.
For example: `sqlite`, `postgresql` or `mysql`

The `Database` interface should be extended with an additional `getDialect` method.
It should return the dialect or the connector that the database is using.

This would make integrating `db0` with other libraries more straight forward.

I was wondering if these types should also be generic, so that other adapters/drivers could narrow allowing only specific dialects of `db0` instances to be provided as dependency, like `Database<"sqlite" | "postgresql">`.

Related: https://github.com/unjs/unstorage/pull/476

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Good idea! Added in https://github.com/unjs/db0/pull/59
