### ISSUE TITLE
Relax peer dependencies

### ISSUE THREAD

**Issue by kingyue737** [unjs/db0#113]
### Describe the feature

https://github.com/unjs/db0 has not been maintained since its release and the database layer is an experimental feature. 
Users always need to override the outdated dependencies of `db0`. For example:
```json
{
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "db0>drizzle-orm": "^0.33.0"
      }
    },
  },
}
```
Could we make `db0` optional?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
I appreciate the issue. db0 will be eventually a non experimental feature so instead i have moved your issue to db0 repo to see how we can relax db0's peer deps :)

**Comment by backrunner** [comment]
I met an issue that I install a module (`@sidebase/nuxt-auth`) which depends on `nitropack`, and the `nitropack` depends on `db0`, which will introduce an incorrect version of peer dependency warning into my project. The module is totally not related on anything about database, but it will introduce a totally non-sense version limitation to `drizzle-orm`, IMO this is not an appropriate behavior.
