### ISSUE TITLE
Issues with peer dependencies with @libsql/client

### ISSUE THREAD

**Issue by drq001out** [unjs/db0#81]
### Environment

18.x +

### Reproduction

 WARN  Issues with peer dependencies found
.
└─┬ db0 0.1.4
  └── ✕ unmet peer @libsql/client@^0.5.2: found 0.6.0

### Describe the bug

the turso (@libsql/client) package is updated on 0.6.0, but the peer dependency is 0.5.2, the top version only can update to 0.5.6 .
I used at the Netlify App, so I must add ENV NPM_FLAGS = "--force" to built.

Sorry, I am not good at English

**Comment by pi0** [comment]
hi, we have relaxed deps in next version.
